[versions]
accompanist = "0.10.0"
activity-compose = "1.3.0-alpha08"
appcompat = "1.3.0"
core = "1.5.0"
compose = "1.0.0-beta07"
exoPlayer = "2.14.0"
koin = "2.2.3"
kotlin = "1.4.32"
retrofit = "2.9.0"
room = "2.3.0"

[libraries]
android-gradle-plugin = "com.android.tools.build:gradle:7.0.0-beta01"
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
versionsCheck-gradle-plugin = "com.github.ben-manes:gradle-versions-plugin:0.38.0"

compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
jetpact-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }

appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
accompanist-coil = { module = "com.google.accompanist:accompanist-coil", version.ref = "accompanist" }
core = { module = "androidx.core:core-ktx", version.ref = "core" }
exoplayer-core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exoPlayer" }
exoplayer-hls = { module = "com.google.android.exoplayer:exoplayer-hls", version.ref = "exoPlayer" }
exoplayer-ui = { module = "com.google.android.exoplayer:exoplayer-ui", version.ref = "exoPlayer" }
exoplayer-extension-mediasession = { module = "com.google.android.exoplayer:extension-mediasession", version.ref = "exoPlayer" }
glide = "com.github.bumptech.glide:glide:4.12.0"
gson = "com.google.code.gson:gson:2.8.6"
koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koinViewModel = { module = "io.insert-koin:koin-androidx-viewmodel", version.ref = "koin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-ktx:2.3.1"
material = "com.google.android.material:material:1.3.0"
media = "androidx.media:media:1.3.1"
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

[bundles]
compose = ["compose-ui", "jetpact-compose-material"]
exoPlayer = ["exoplayer-core", "exoplayer-hls", "exoplayer-ui", "exoplayer-extension-mediasession"]
room = ["room-runtime", "room-ktx"]
retrofit = ["retrofit", "retrofitGson"]